aptProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path
from .import views

app_name = 'main'
urlpatterns = [
    path('', views.dataFormulate),
    # path('home',views.backtoHome, name='home'),
    path('home', views.guInfoCreate, name="guSelect"),
    path('dong',views.dong_select, name="dongSelect"),
    path('apt',views.apt_select, name="aptSelect"),
    path('extra',views.extraInfo_select, name="extraSelect"),
    path('predict', views.predictInput, name="predictInput"),

]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render,redirect
import pandas as pd
import numpy as np
import lightgbm as lgb
from sklearn.preprocessing import LabelEncoder

import plotly.io as pio
pio.templates.default = 'plotly_dark'

import pandas as pd
import numpy as np
import requests
from urllib.parse import urlparse
import urllib.parse
import time
import plotly.express as px
import plotly.graph_objects as go
from haversine import haversine
import chart_studio
import chart_studio.plotly as py
import chart_studio.tools as tls

# Create your views here.

lgb_model = ""
predictedValue = ''
predictedGu = ""
predictedDong = ""
predictedApt = ""
parkMapLink = ''

def backtoHome(request):

    return render(request, "index.html")

def dongTest(request):
        selected_gu = request.GET['selected_gu']

        data = pd.read_csv('final_end.csv',index_col = 0)
        seoulDongList = data["dong"].unique()

        dongList = []

        with open("gu/"+selected_gu+".txt","r", encoding='utf-8') as f:
            Lines = f.readline()
            selectdDongList = Lines.split(",")

        finalDongList = []
        for i in seoulDongList:
            if i in selectdDongList:
                finalDongList.append(i)

        return render(request, "dongSelect.html",{"dongInfo":finalDongList,"guSelected": selected_gu})





def dataFormulate(request):
    data = pd.read_csv('data.csv',index_col = 0)

    from sklearn.model_selection import train_test_split
    Y = data['price(manwon)']
    X = data.drop('price(manwon)',axis=1)
    X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.1 , random_state = 1234)

    train_ds = lgb.Dataset(X_train,label=Y_train)
    test_ds = lgb.Dataset(X_test,label=Y_test)
    params = {"objective" : "regression", "metric" : "mse", 'n_estimators':1000,"num_leaves" : 20, "learning_rate" : 0.1, "bagging_fraction" : 0.8, 'max_depth': 6}#15000번 테스트
    global lgb_model
    lgb_model = lgb.train(params, train_ds, 1000, test_ds, verbose_eval=1000, early_stopping_rounds=100)

    return redirect("main:guSelect")

#기타 정보입력받는 뷰
def extraInfo_select(request):

    selected_gu = request.POST['guSelected']
    selected_dong = request.POST['dongSelected']
    selected_apt = request.POST['slct']

    return render(request, "extraSelect.html",{"aptSelected": selected_apt, "dongSelected":selected_dong,"guSelected": selected_gu})

def predictInput(request):
        selected_gu = request.POST['guSelected']
        selected_dong = request.POST['dongSelected']
        selected_apt = request.POST['aptSelected']
        selectedDate = request.POST['dateSelected']
        selectedSize = int(request.POST['sizeSelected']) *  3.31

        selectedYear, selectedMonth = map(int,selectedDate.split("-"))

        #아파트랑 구 번호로 변환

        data = pd.read_csv('final_end.csv')

        dong_enc = LabelEncoder().fit_transform(data['dong'])
        apt_name_enc = LabelEncoder().fit_transform(data['apt_name'])

        dong_num = pd.DataFrame({'enc':dong_enc,'dong':pd.read_csv('final_end.csv')['dong']})
        dong_num = dong_num.drop_duplicates().reset_index(drop=True)
        found_dong_num = int(dong_num[dong_num['dong']==selected_dong]['enc'])

        apt_num = pd.DataFrame({'enc':apt_name_enc,'apt':pd.read_csv('final_end.csv')['apt_name']})
        apt_num = apt_num.drop_duplicates().reset_index(drop=True)
        found_apt_num =  int(apt_num[apt_num['apt']==selected_apt]['enc'])

        result = price_pred(x1=selectedYear,x2=selectedMonth,x3=found_dong_num,x4=found_apt_num, x5=selectedSize)
        price = result[0]
        global predictedValue
        global predictedGu
        global predictedDong
        global predictedApt
        global parkMapLink
        predictedGu = selected_gu
        predictedDong = selected_dong
        predictedApt = selected_apt
        predictedValue = str(int(price // 10000))+ "억 "+str(int(price % 10000)) + "만원"

        try:
            parkMapLink = parkMapInfoCreate(predictedApt)
        except:
            parkMapLink = ''

        return redirect("main:guSelect")

#최종화면에서 가격예측해주는 함수
def price_pred(x1, x2,x3,x4, x5=77.95, x6=0,x7=0,x8=0,x9=9,x10=1998):
    mmm=[{'use_area(m2)': x5, 'transaction_year':x1,'transaction_month':x2, 'date(1~10)':x6,'date(11~20)':x7,'date(21~)':x8,'floor':x9,'year_found':x10,'dong_enc':x3,'apt_name_enc':x4}]
    inp=pd.DataFrame(mmm)
    global lgb_model
    return lgb_model.predict(inp)

#동선택 뷰
def dong_select(request):

    selected_gu = request.POST['slct']

    data = pd.read_csv('final_end.csv',index_col = 0)
    seoulDongList = data["dong"].unique()

    dongList = []

    with open("gu/"+selected_gu+".txt","r", encoding='utf-8') as f:
        Lines = f.readline()
        selectdDongList = Lines.split(",")

    finalDongList = []
    for i in seoulDongList:
        if i in selectdDongList:
            finalDongList.append(i)

    return render(request, "dongSelect.html",{"dongInfo":finalDongList,"guSelected": selected_gu})

def apt_select(request):

    selected_gu = request.POST['guSelected']
    selected_dong = request.POST['slct']

    data = pd.read_csv('final_end.csv',index_col = 0)

    grouped = data.groupby('dong').get_group(selected_dong)["apt_name"].unique()

    return render(request, "aptSelect.html", {"aptInfo":grouped, "guSelected" : selected_gu, "dongSelected" : selected_dong})


def guInfoCreate(request):
    gu_dict = ['종로구','중구','용산구','성동구','광진구','동대문구','중랑구','성북구','강북구','도봉구','노원구','은평구','서대문구','마포구','양천구','강서구','구로구','금천구','영등포구','동작구','관악구','서초구','강남구','송파구','강동구']

    global predictedValue
    global predictedGu
    global predictedDong
    global predictedApt
    global parkMapLink

    predicted = predictedValue
    # for i in gu_dict:
    #     with open("gu/"+i+".txt","r", encoding='utf-8') as f:
    #         Lines = f.readline()
    #         dongList = Lines.split(",")
    #         print(dongList)

    return render(request, "index.html", {"guInfo":gu_dict, "predictedPrice": predicted, "predictedGu":predictedGu,  "predictedDong":predictedDong,  "predictedApt":predictedApt, 'parkMapLink' : parkMapLink})

def parkMapInfoCreate(address):
    apt_address = pd.read_csv('apt_address.csv')
    park_after = pd.read_csv('parkWithLatLng_after.csv',usecols = ['city','gu','dong','park_name','park_type','park_area','name','id','lat','lng'])

    username='Jeehoon-K'
    api_key= '2mJ6DMkHJjm1oGEBYyn2'
    chart_studio.tools.set_credentials_file(username=username,api_key=api_key)
    fig = get_map(address, park_after,apt_address)
    return py.plot(fig, filename = 'Monochrome', auto_open=False)

def id(name, apt_address):
  address = apt_address[apt_address['apt_name']==str(name)].reset_index()['address'][0]
  url = 'https://dapi.kakao.com/v2/local/search/address.json?&query=' + str(address)
  result = requests.get(urlparse(url).geturl(), headers={'Authorization': 'KakaoAK 10faa6da25b75ef0a75b555ae4e5d64e'}).json()
  match_first = result['documents'][0]['address']
  lat = float(match_first['y'])
  lng = float(match_first['x'])
  return [lat, lng]

def get_close_index(apt_name, park_after, apt_address):
  P = park_after['lat']-id(apt_name, apt_address)[0]
  Q = park_after['lng']-id(apt_name, apt_address)[1]
  s = [k for k in range(len(park_after)) if -0.01<P[k]<0.01]
  l = [k for k in s if -0.02<Q[k]<0.02]
  f = [k for k in l if haversine(id(apt_name,apt_address), [park_after['lat'][k],park_after['lng'][k]], unit = 'm') <= 500]
  return f

def get_map(address, park_after, apt_address):
  f = get_close_index(address, park_after,apt_address)
  C = []
  for k in range(len(park_after)):
    if k not in f:
      C.append('공원')
    else:
      C.append('근방 공원')

  park_after['color']=C

  px.set_mapbox_access_token('pk.eyJ1Ijoiam9objEwMTAxMCIsImEiOiJja2tjOXN5OG0wbDA2Mm5wODVhZ3R1OW5rIn0.j37zc9C6hM8DCo0fLlRirg')

  data = park_after.copy()
  data['park_area'] = np.log(data['park_area'])
  fig = go.Figure()
  fig = px.scatter_mapbox(data, lat="lat", lon="lng",
                          size= "park_area",
                          hover_name="name",
                          size_max=15,
                          zoom=13,
                          center={'lat':id(address,apt_address)[0],'lon':id(address,apt_address)[1]},
                          color = 'color',
                          title = '내 아파트 주변 공원'
                          )
  fig.update_layout(mapbox_style="carto-darkmatter")


  return fig

main/templates/aptSelect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>아파트선택</title>
    <style>

      body {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        height: 100vh;
        background: #000;
      }
      h1 {
        margin: 0 0 0.25em;
        color : #fff;
      }
      /* Reset Select */
      select {
        -webkit-appearance: none;
        -moz-appearance: none;
        -ms-appearance: none;
        appearance: none;
        outline: 0;
        box-shadow: none;
        border: 0 !important;
        background: #4070f4;
        background-image: none;
      }
      /* Remove IE arrow */
      select::-ms-expand {
        display: none;
      }
      /* Custom Select */
      .select {
        position: relative;
        display: flex;
        width: 20em;
        height: 3em;
        line-height: 3;
        background: #4070f4;
        overflow: hidden;
        border-radius: .25em;
      }
      select {
        flex: 1;
        padding: 0 .5em;
        color: #fff;
        cursor: pointer;
      }
      /* Arrow */
      .select::after {
        content: '\25BC';
        position: absolute;
        top: 0;
        right: 0;
        padding: 0 1em;
        background: #34495e;
        cursor: pointer;
        pointer-events: none;
        -webkit-transition: .25s all ease;
        -o-transition: .25s all ease;
        transition: .25s all ease;
      }
      /* Transition */
      .select:hover::after {
        color: #f39c12;
      }

button {
  font-size: 1em;
  background: #4070f4;
  color: #fff;
  border: 0.25rem solid #4070f4;
  padding: 0.85em 0.75em;
  margin: 1rem;
  position: absolute;
  right:40%;
  overflow: hidden;
}
button:hover {
  color: #3498db;
}
button::after {
  content: "";
  background: #ecf0f1;
  position: absolute;
  z-index: -1;
  padding: 0.85em 0.75em;
  display: block;
}
button[class^="slide"]::after {
  transition: all 0.35s;
}
button[class^="slide"]:hover::after {
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  transition: all 0.35s;
}
button.slide_from_left::after {
  top: 0;
  bottom: 0;
  left: -100%;
  right: 100%;
}
button.slide_from_right::after {
  top: 0;
  bottom: 0;
  left: 100%;
  right: -100%;
}
button.slide_from_top::after {
  left: 0;
  right: 0;
  top: -100%;
  bottom: 100%;
}
button.slide_from_bottom::after {
  left: 0;
  right: 0;
  top: 100%;
  bottom: -100%;
}
button[class^="grow"]::after {
  transition: all 0.3s ease;
}
button[class^="grow"]:hover::after {
  transition: all 0.3s ease-out;
}
button.grow_box::after {
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  transform: scale(0, 0);
}
button.grow_box:hover::after {
  transform: scale(1, 1);
}
button.grow_ellipse::after {
  border-radius: 50%;
  left: -50%;
  right: -50%;
  top: -150%;
  bottom: -150%;
  line-height: 8.34em;
  transform: scale(0, 0);
}
button.grow_ellipse:hover::after {
  transform: scale(1, 1);
}
button.grow_skew_forward::after {
  left: -20%;
  right: -20%;
  top: 0;
  bottom: 0;
  transform: skewX(-45deg) scale(0, 1);
}
button.grow_skew_forward:hover::after {
  transform: skewX(-45deg) scale(1, 1);
}
button.grow_skew_backward::after {
  left: -20%;
  right: -20%;
  top: 0;
  bottom: 0;
  transform: skewX(45deg) scale(0, 1);
}
button.grow_skew_backward:hover::after {
  transform: skewX(45deg) scale(1, 1);
}
button.grow_spin::after {
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  transform: scale(0, 0) rotate(-180deg);
}
button.grow_spin:hover::after {
  transform: scale(1, 1) rotate(0deg);
}
    </style>
</head>
<body>
  <link rel="stylesheet" href="/static/css/styles.css">
  <h1>아파트를 선택하세요</h1>
  <br></br>
  <form action="{% url 'main:extraSelect' %}" method="POST" enctype="multipart/form-data" class="form-horizontal">
    {% csrf_token %}
  <div class="select">
    <input type="hidden" name="guSelected" value="{{guSelected}}"></input>
    <input type="hidden" name="dongSelected" value="{{dongSelected}}"></input>
    <select name="slct" id="slct">
      <option selected disabled>보기에서 선택하세요</option>
      {% for apt in aptInfo %}
      <option value='{{apt}}' name='selectedApt'> {{apt}}</option>
      {% endfor %}
    </select>
  </div>
  <!-- <button type = submit id="nextButton" style = "visibility: hidden">Next</button> -->
  <div>
    <button class="slide_from_left" type = submit id="nextButton" style = "visibility: hidden">NEXT</button>
  </div>
  </form>
  <script type="text/javascript">

    var slctBox = document.getElementById("slct");
    var nextButton = document.getElementById("nextButton");

    slctBox.addEventListener("change",showNextButton);

    function showNextButton(){
      nextButton.style.visibility = 'visible';
    }

  </script>
</body>
</html>

main/templates/dongSelect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>동선택</title>
    <style>
      body {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        height: 100vh;
        background:#000000;
      }
      h1 {
        margin: 0 0 0.25em;
        color: #fff;
      }
      /* Reset Select */
      select {
        -webkit-appearance: none;
        -moz-appearance: none;
        -ms-appearance: none;
        appearance: none;
        outline: 0;
        box-shadow: none;
        border: 0 !important;
        background: #4070f4;
        background-image: none;
      }
      /* Remove IE arrow */
      select::-ms-expand {
        display: none;
      }
      /* Custom Select */
      .select {
        position: relative;
        display: flex;
        width: 20em;
        height: 3em;
        line-height: 3;
        background: #4070f4;
        overflow: hidden;
        border-radius: .25em;
      }
      select {
        flex: 1;
        padding: 0 .5em;
        color: #fff;
        cursor: pointer;
      }
      /* Arrow */
      .select::after {
        content: '\25BC';
        position: absolute;
        top: 0;
        right: 0;
        padding: 0 1em;
        background: #34495e;
        cursor: pointer;
        pointer-events: none;
        -webkit-transition: .25s all ease;
        -o-transition: .25s all ease;
        transition: .25s all ease;
      }
      /* Transition */
      .select:hover::after {
        color: #f39c12;
      }

button {
  font-size: 1em;
  background: #4070f4;
  color: #fff;
  border: 0.25rem solid #4070f4;
  padding: 0.85em 0.75em;
  margin: 1rem;
  position: absolute;
  right:40%;
  overflow: hidden;
}
button:hover {
  color: #3498db;
}
button::after {
  content: "";
  background: #ecf0f1;
  position: absolute;
  z-index: -1;
  padding: 0.85em 0.75em;
  display: block;
}
button[class^="slide"]::after {
  transition: all 0.35s;
}
button[class^="slide"]:hover::after {
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  transition: all 0.35s;
}
button.slide_from_left::after {
  top: 0;
  bottom: 0;
  left: -100%;
  right: 100%;
}
button.slide_from_right::after {
  top: 0;
  bottom: 0;
  left: 100%;
  right: -100%;
}
button.slide_from_top::after {
  left: 0;
  right: 0;
  top: -100%;
  bottom: 100%;
}
button.slide_from_bottom::after {
  left: 0;
  right: 0;
  top: 100%;
  bottom: -100%;
}
button[class^="grow"]::after {
  transition: all 0.3s ease;
}
button[class^="grow"]:hover::after {
  transition: all 0.3s ease-out;
}
button.grow_box::after {
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  transform: scale(0, 0);
}
button.grow_box:hover::after {
  transform: scale(1, 1);
}
button.grow_ellipse::after {
  border-radius: 50%;
  left: -50%;
  right: -50%;
  top: -150%;
  bottom: -150%;
  line-height: 8.34em;
  transform: scale(0, 0);
}
button.grow_ellipse:hover::after {
  transform: scale(1, 1);
}
button.grow_skew_forward::after {
  left: -20%;
  right: -20%;
  top: 0;
  bottom: 0;
  transform: skewX(-45deg) scale(0, 1);
}
button.grow_skew_forward:hover::after {
  transform: skewX(-45deg) scale(1, 1);
}
button.grow_skew_backward::after {
  left: -20%;
  right: -20%;
  top: 0;
  bottom: 0;
  transform: skewX(45deg) scale(0, 1);
}
button.grow_skew_backward:hover::after {
  transform: skewX(45deg) scale(1, 1);
}
button.grow_spin::after {
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  transform: scale(0, 0) rotate(-180deg);
}
button.grow_spin:hover::after {
  transform: scale(1, 1) rotate(0deg);
}
    </style>
</head>
<body>
  <link rel="stylesheet" href="/static/css/styles.css">
  <h1>동을 선택하세요</h1>
  <br></br>
  <form action="{% url 'main:aptSelect' %}" method="POST" enctype="multipart/form-data" class="form-horizontal">
    {% csrf_token %}
    <div class="about__img"></div>
  <div class="select">
    <input type="hidden" name="guSelected" value="{{guSelected}}"></input>
    <select name="slct" id="slct">
      <option selected disabled>보기에서 선택하세요</option>
      {% for dong in dongInfo %}
      <option value='{{dong}}' name='selectedDong'> {{dong}}</option>
      {% endfor %}
    </select>
  </div>
  <!-- <button type = submit id="nextButton" style = "visibility: hidden">Next</button> -->
  <div>
  <button class="slide_from_left" type = submit id="nextButton" style = "visibility: hidden">NEXT</button>
  </div>
  </form>
  <script type="text/javascript">

    var slctBox = document.getElementById("slct");
    var nextButton = document.getElementById("nextButton");

    slctBox.addEventListener("change",showNextButton);

    function showNextButton(){
      nextButton.style.visibility = 'visible';
    }

  </script>
</body>
</html>

main/templates/extraSelect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>기타정보선택</title>
    <style>

    * { box-sizing:border-box; }

/* basic stylings ------------------------------------------ */
body 				 { background:url(https://scotch.io/wp-content/uploads/2014/07/61.jpg); }
.container 		{
  font-family:'Roboto';
  width:600px;
  margin:30px auto 0;
  display:block;
  background:#fff;
  padding:10px 50px 50px;
}
h2 		 {
  text-align:center;
  margin-bottom:50px;
  color : #4070f4;
}
h2 small {
  font-weight:normal;
  color:#888;
  display:block;
}
.footer 	{ text-align:center; }
.footer a  { color:#53B2C8; }

/* form starting stylings ------------------------------- */
.group 			  {
  position:relative;
  margin-bottom:45px;
}
input 				{
  font-size:18px;
  padding:10px 10px 10px 5px;
  display:block;
  width:300px;
  border:none;
  border-bottom:1px solid #757575;
}
input:focus 		{ outline:none; }

/* LABEL ======================================= */
label 				 {
  color:#999;
  font-size:18px;
  font-weight:normal;
  position:absolute;
  pointer-events:none;
  left:5px;
  top:10px;
  transition:0.2s ease all;
  -moz-transition:0.2s ease all;
  -webkit-transition:0.2s ease all;
}

/* active state */
input:focus ~ label, input:valid ~ label 		{
  top:-20px;
  font-size:14px;
  color:#5264AE;
}

/* BOTTOM BARS ================================= */
.bar 	{ position:relative; display:block; width:300px; }
.bar:before, .bar:after 	{
  content:'';
  height:2px;
  width:0;
  bottom:1px;
  position:absolute;
  background:#5264AE;
  transition:0.2s ease all;
  -moz-transition:0.2s ease all;
  -webkit-transition:0.2s ease all;
}
.bar:before {
  left:50%;
}
.bar:after {
  right:50%;
}

/* active state */
input:focus ~ .bar:before, input:focus ~ .bar:after {
  width:50%;
}

/* HIGHLIGHTER ================================== */
.highlight {
  position:absolute;
  height:60%;
  width:100px;
  top:25%;
  left:0;
  pointer-events:none;
  opacity:0.5;
}

/* active state */
input:focus ~ .highlight {
  -webkit-animation:inputHighlighter 0.3s ease;
  -moz-animation:inputHighlighter 0.3s ease;
  animation:inputHighlighter 0.3s ease;
}

/* ANIMATIONS ================ */
@-webkit-keyframes inputHighlighter {
	from { background:#5264AE; }
  to 	{ width:0; background:transparent; }
}
@-moz-keyframes inputHighlighter {
	from { background:#5264AE; }
  to 	{ width:0; background:transparent; }
}
@keyframes inputHighlighter {
	from { background:#5264AE; }
  to 	{ width:0; background:transparent; }
}
      body {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        height: 100vh;
        background: #000;
      }


button {
  font-size: 1em;
  background: #4070f4;
  color: #fff;
  
  padding: 0.85em 0.75em;
  margin: 1rem;
  position: absolute;
  right:35%;
  bottom :30%;
  overflow: hidden;
}
button:hover {
  color: #3498db;
}
button::after {
  content: "";
  background: #ecf0f1;
  position: absolute;
  z-index: -1;
  padding: 0.85em 0.75em;
  display: block;
}
button[class^="slide"]::after {
  transition: all 0.35s;
}
button[class^="slide"]:hover::after {
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  transition: all 0.35s;
}
button.slide_from_left::after {
  top: 0;
  bottom: 0;
  left: -100%;
  right: 100%;
}
button.slide_from_right::after {
  top: 0;
  bottom: 0;
  left: 100%;
  right: -100%;
}
button.slide_from_top::after {
  left: 0;
  right: 0;
  top: -100%;
  bottom: 100%;
}
button.slide_from_bottom::after {
  left: 0;
  right: 0;
  top: 100%;
  bottom: -100%;
}
button[class^="grow"]::after {
  transition: all 0.3s ease;
}
button[class^="grow"]:hover::after {
  transition: all 0.3s ease-out;
}
button.grow_box::after {
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  transform: scale(0, 0);
}
button.grow_box:hover::after {
  transform: scale(1, 1);
}
button.grow_ellipse::after {
  border-radius: 50%;
  left: -50%;
  right: -50%;
  top: -150%;
  bottom: -150%;
  line-height: 8.34em;
  transform: scale(0, 0);
}
button.grow_ellipse:hover::after {
  transform: scale(1, 1);
}
button.grow_skew_forward::after {
  left: -20%;
  right: -20%;
  top: 0;
  bottom: 0;
  transform: skewX(-45deg) scale(0, 1);
}
button.grow_skew_forward:hover::after {
  transform: skewX(-45deg) scale(1, 1);
}
button.grow_skew_backward::after {
  left: -20%;
  right: -20%;
  top: 0;
  bottom: 0;
  transform: skewX(45deg) scale(0, 1);
}
button.grow_skew_backward:hover::after {
  transform: skewX(45deg) scale(1, 1);
}
button.grow_spin::after {
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  transform: scale(0, 0) rotate(-180deg);
}
button.grow_spin:hover::after {
  transform: scale(1, 1) rotate(0deg);
}
    </style>
</head>
<body>
  <link rel="stylesheet" href="/static/css/styles.css">
  <div class="info__container">

    <h1 class="title-title"> 원하는 크기(평)와 </br>예상 구매일을 입력해주세요</h1>
    <br>
    <br>
    
    <form action="{% url 'main:predictInput' %}" method="POST" enctype="multipart/form-data" class="form-horizontal">
      
        {% csrf_token %}

      <div class="info__container bd-grid">
        <div class="about__img">

      <input type="hidden" name="guSelected" value="{{guSelected}}"></input>
      <input type="hidden" name="dongSelected" value="{{dongSelected}}"></input>
      <input type="hidden" name="aptSelected" value="{{aptSelected}}"></input>
      <div class="group">
        <input type="number" name = "sizeSelected" required min="5" max="100">
        <span class="highlight"></span>
        <span class="bar"></span>
      </div>
    </div>

      <div class="group">
        <input type="month" required name="dateSelected" min="2021-01" max="2070-12">
        <span class="highlight"></span>
        <span class="bar"></span>

      </div>
      <button class="slide_from_right" type = submit id="nextButton" >NEXT</button>
    

      <script src="/static/js/main.js"></script>
    

    </form>
</body>
</html>